-- ============================================================
-- Email notifications
-- ============================================================
-- Les triggers pg_net ont été retirés car trop fragiles :
--   • Nécessitent l'extension pg_net
--   • Nécessitent de stocker l'anon key dans Postgres (permission refusée)
--   • Appels HTTP asynchrones non fiables
--
-- Le mécanisme PRIMAIRE est l'appel direct depuis le frontend
-- (booking.service.ts, contact.service.ts) via supabase.functions.invoke()
-- qui gère l'authentification automatiquement.
--
-- Les Edge Functions restent déployées et sont appelées directement
-- par le frontend après chaque insertion réussie.
-- ============================================================
